spring:
  application:
    name: gateway
server:
  port: 8082
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:gateway.jks
    key-store-password: password
    key-alias: gateway
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:gateway.jks
    trust-store-password: password
    trust-store-type: JKS
app:
  serverUrl: "${SERVER_URL}"